spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://104.153.100.186:3306/demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  jpa:
    hibernate.ddl-auto: update
    show-sql: true

#format json
#jacksonserialization.indent_output: true